// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AwardBadge(ctx context.Context, arg AwardBadgeParams) error
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CreateFocusSession(ctx context.Context, arg CreateFocusSessionParams) (FocusSession, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeactivateUser(ctx context.Context, id int32) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteJobByID(ctx context.Context, id int32) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteOldCacheForUser(ctx context.Context, userID int32) error
	DeleteRefreshToken(ctx context.Context, token string) error
	DeleteUserRefreshTokens(ctx context.Context, userID int32) error
	GetActiveSession(ctx context.Context, userID int32) (FocusSession, error)
	GetAllBadgeDefinitions(ctx context.Context) ([]BadgeDefinition, error)
	GetCachedJobByID(ctx context.Context, arg GetCachedJobByIDParams) (SerpJobCache, error)
	GetCachedJobsByUserID(ctx context.Context, arg GetCachedJobsByUserIDParams) ([]SerpJobCache, error)
	GetFocusSessionByID(ctx context.Context, id int32) (FocusSession, error)
	GetJobByID(ctx context.Context, id int32) (Job, error)
	GetJobs(ctx context.Context, userID int32) ([]Job, error)
	GetLatestCacheFetchTime(ctx context.Context, userID int32) (pgtype.Timestamp, error)
	GetProgressSummary(ctx context.Context, arg GetProgressSummaryParams) (GetProgressSummaryRow, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetStreak(ctx context.Context, userID int32) (Streak, error)
	GetUnreadCount(ctx context.Context, userID int32) (int64, error)
	GetUserBadgeCount(ctx context.Context, userID int32) (int64, error)
	GetUserBadges(ctx context.Context, userID int32) ([]GetUserBadgesRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error)
	GetUserProfileByUserID(ctx context.Context, userID int32) (UserProfile, error)
	GetUserSessionHistory(ctx context.Context, arg GetUserSessionHistoryParams) ([]FocusSession, error)
	GetUsersWithNoSessionToday(ctx context.Context) ([]int32, error)
	MarkAllNotificationsRead(ctx context.Context, userID int32) error
	MarkJobSavedToTracker(ctx context.Context, arg MarkJobSavedToTrackerParams) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	UpdateFocusSession(ctx context.Context, arg UpdateFocusSessionParams) (FocusSession, error)
	UpdateJobByID(ctx context.Context, arg UpdateJobByIDParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
	UploadUserCV(ctx context.Context, arg UploadUserCVParams) (UserProfile, error)
	UpsertDailyProgress(ctx context.Context, arg UpsertDailyProgressParams) error
	UpsertSerpJobCache(ctx context.Context, arg UpsertSerpJobCacheParams) (SerpJobCache, error)
	UpsertStreak(ctx context.Context, arg UpsertStreakParams) (Streak, error)
}

var _ Querier = (*Queries)(nil)
