// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: serp_job_cache.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldCacheForUser = `-- name: DeleteOldCacheForUser :exec
DELETE FROM serp_job_cache
WHERE user_id = $1
  AND fetched_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) DeleteOldCacheForUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteOldCacheForUser, userID)
	return err
}

const getCachedJobByID = `-- name: GetCachedJobByID :one
SELECT id, user_id, external_id, title, company_name, location, description, link, platform, posted_at, salary, saved_to_tracker, fetched_at FROM serp_job_cache
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetCachedJobByIDParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) GetCachedJobByID(ctx context.Context, arg GetCachedJobByIDParams) (SerpJobCache, error) {
	row := q.db.QueryRow(ctx, getCachedJobByID, arg.ID, arg.UserID)
	var i SerpJobCache
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Title,
		&i.CompanyName,
		&i.Location,
		&i.Description,
		&i.Link,
		&i.Platform,
		&i.PostedAt,
		&i.Salary,
		&i.SavedToTracker,
		&i.FetchedAt,
	)
	return i, err
}

const getCachedJobsByUserID = `-- name: GetCachedJobsByUserID :many
SELECT id, user_id, external_id, title, company_name, location, description, link, platform, posted_at, salary, saved_to_tracker, fetched_at FROM serp_job_cache
WHERE user_id = $1
ORDER BY fetched_at DESC
LIMIT $2 OFFSET $3
`

type GetCachedJobsByUserIDParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetCachedJobsByUserID(ctx context.Context, arg GetCachedJobsByUserIDParams) ([]SerpJobCache, error) {
	rows, err := q.db.Query(ctx, getCachedJobsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SerpJobCache{}
	for rows.Next() {
		var i SerpJobCache
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalID,
			&i.Title,
			&i.CompanyName,
			&i.Location,
			&i.Description,
			&i.Link,
			&i.Platform,
			&i.PostedAt,
			&i.Salary,
			&i.SavedToTracker,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCacheFetchTime = `-- name: GetLatestCacheFetchTime :one
SELECT fetched_at FROM serp_job_cache
WHERE user_id = $1
ORDER BY fetched_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCacheFetchTime(ctx context.Context, userID int32) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, getLatestCacheFetchTime, userID)
	var fetched_at pgtype.Timestamp
	err := row.Scan(&fetched_at)
	return fetched_at, err
}

const markJobSavedToTracker = `-- name: MarkJobSavedToTracker :exec
UPDATE serp_job_cache
SET saved_to_tracker = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkJobSavedToTrackerParams struct {
	ID     int32 `json:"id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) MarkJobSavedToTracker(ctx context.Context, arg MarkJobSavedToTrackerParams) error {
	_, err := q.db.Exec(ctx, markJobSavedToTracker, arg.ID, arg.UserID)
	return err
}

const upsertSerpJobCache = `-- name: UpsertSerpJobCache :one
INSERT INTO serp_job_cache (
    user_id,
    external_id,
    title,
    company_name,
    location,
    description,
    link,
    platform,
    posted_at,
    salary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) ON CONFLICT (user_id, external_id) DO UPDATE SET
    title        = EXCLUDED.title,
    company_name = EXCLUDED.company_name,
    location     = EXCLUDED.location,
    description  = EXCLUDED.description,
    link         = EXCLUDED.link,
    platform     = EXCLUDED.platform,
    posted_at    = EXCLUDED.posted_at,
    salary       = EXCLUDED.salary,
    fetched_at   = NOW()
RETURNING id, user_id, external_id, title, company_name, location, description, link, platform, posted_at, salary, saved_to_tracker, fetched_at
`

type UpsertSerpJobCacheParams struct {
	UserID      int32   `json:"user_id"`
	ExternalID  string  `json:"external_id"`
	Title       string  `json:"title"`
	CompanyName *string `json:"company_name"`
	Location    *string `json:"location"`
	Description *string `json:"description"`
	Link        *string `json:"link"`
	Platform    *string `json:"platform"`
	PostedAt    *string `json:"posted_at"`
	Salary      *string `json:"salary"`
}

func (q *Queries) UpsertSerpJobCache(ctx context.Context, arg UpsertSerpJobCacheParams) (SerpJobCache, error) {
	row := q.db.QueryRow(ctx, upsertSerpJobCache,
		arg.UserID,
		arg.ExternalID,
		arg.Title,
		arg.CompanyName,
		arg.Location,
		arg.Description,
		arg.Link,
		arg.Platform,
		arg.PostedAt,
		arg.Salary,
	)
	var i SerpJobCache
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Title,
		&i.CompanyName,
		&i.Location,
		&i.Description,
		&i.Link,
		&i.Platform,
		&i.PostedAt,
		&i.Salary,
		&i.SavedToTracker,
		&i.FetchedAt,
	)
	return i, err
}
